---
title: "Homework 1"
author: "Zhiquan Chen"
date: "2026-09-23"
output: github_document
---
# Problem 1
```{r message=FALSE, warning=FALSE}
library(tidyverse)
data("penguins", package = "palmerpenguins")
var_names <- paste0("`", names(penguins), "`", collapse = ", ")
```

The `penguins` dataset contains data for different penguin species. Important variables include `r var_names`.

The size of this dataset is `r nrow(penguins)` rows (observations) and `r ncol(penguins)` columns (variables). 

The mean flipper length for the penguins is `r round(mean(penguins$flipper_length_mm, na.rm = TRUE), 2)` mm.

```{r}
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) +
  geom_point()

ggsave("penguins_scatterplot.png")
```


# Problem 2

```{r}
p2_df = tibble(
  norm_samp = rnorm(10),
  log_vec = norm_samp > 0,
  char_vec = letters[1:10],
  fac_vec = factor(rep(c("Level A", "Level B", "Level C"), length.out = 10))
)
```

```{r}
mean(pull(p2_df, norm_samp)) 
mean(pull(p2_df, log_vec))  
mean(pull(p2_df, char_vec))  
mean(pull(p2_df, fac_vec)) 
```

```{r,eval=FALSE}
as.numeric(pull(p2_df, log_vec))
as.numeric(pull(p2_df, char_vec))
as.numeric(pull(p2_df, fac_vec))
```


